name: ibeacon_plugin
description: "A new Flutter plugin project."
version: 0.0.1

environment:
  sdk: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.pandora_cube.ibeacon_plugin
        pluginClass: IbeaconPlugin
      ios:
        pluginClass: IbeaconPlugin
